"""D7b stub backend — deterministic, fixed scores for Stage 1.

The stub exists so that D7 orchestration, lifecycle, and telemetry can
be exercised without introducing an LLM confounder.

The ``STUB_REASONING_PREFIX`` is a magic prefix contract. The acceptance
notebook and any downstream consumer MUST be able to assert
``result.d7b_reasoning.startswith(STUB_REASONING_PREFIX)`` to detect
stub mode defensively, redundant with ``d7b_mode == "stub"``.
"""

from __future__ import annotations

from typing import Literal

from agents.critic.batch_context import BatchContext
from agents.critic.d7b_backend import D7bBackend
from strategies.dsl import StrategyDSL

STUB_REASONING_PREFIX = "[STUB REASONING —"

STUB_REASONING = (
    "[STUB REASONING — D7b is in stub mode, no live LLM critic was invoked. "
    "All scores are fixed at 0.5. This text is NOT generated by any model. "
    "Stage 1 uses this stub to establish the D7 orchestration contract without "
    "introducing an LLM confounder. Stage 2 replaces this with a live Sonnet critic.]"
)


class StubD7bBackend(D7bBackend):
    """Deterministic stub D7b backend for Stage 1."""

    @property
    def mode(self) -> Literal["stub"]:
        return "stub"

    def score(
        self,
        dsl: StrategyDSL,
        theme: str,
        batch_context: BatchContext,
    ) -> tuple[dict[str, float], str, dict]:
        scores = {
            "semantic_plausibility": 0.5,
            "semantic_theme_alignment": 0.5,
            "structural_variant_risk": 0.5,
        }
        metadata = {
            "raw_response_path": None,
            "cost_actual_usd": 0.0,
            "input_tokens": 0,
            "output_tokens": 0,
            "retry_count": 0,
        }
        return scores, STUB_REASONING, metadata


__all__ = ["STUB_REASONING", "STUB_REASONING_PREFIX", "StubD7bBackend"]
