"""Shared lineage contract — producer + consumer guards across attestation domains.

This module is the single source of truth for corrected-engine artifact
lineage enforcement (Section RS of
docs/decisions/WF_TEST_BOUNDARY_SEMANTICS.md). Producers
(scripts/run_phase2c_batch_walkforward.py, scripts/run_phase1b_corrected.py,
scripts/run_phase2c_evaluation_gate.py, and any future corrected-engine
artifact producer) AND downstream consumers (DSR/PBO/CPCV/MDS/
strategy-shortlist tooling) must use these helpers to enforce the
hard prohibition: pre-correction artifacts must not be produced or
consumed.

Two attestation domains, kept semantically separate:

1. Walk-forward artifacts (wf_semantics='corrected_test_boundary_v1'):
   produced by run_walk_forward and its downstream batch runners.
   Validated by check_wf_semantics_or_raise.

2. Single-run holdout artifacts (evaluation_semantics='single_run_holdout_v1'):
   produced by single-run evaluations like the PHASE2C_6 regime holdout
   gate. Validated by check_evaluation_semantics_or_raise.

The two helpers do not cross-validate — calling check_wf_semantics_or_raise
on a single-run holdout artifact rejects it (no wf_semantics field), and
vice-versa. This is intentional and prevents accidental cross-domain
consumption.

The producer-side helper (enforce_corrected_engine_lineage) refuses
to run on a HEAD that does not contain the corrected engine commit.
It is shared by both attestation domains because the engine fix is a
prerequisite for either kind of corrected artifact.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

CORRECTED_WF_ENGINE_COMMIT = "eb1c87f"
WF_SEMANTICS_TAG = "corrected_test_boundary_v1"

# Single-run holdout artifact tags (PHASE2C_6 evaluation gate work).
# Separate from WF_SEMANTICS_TAG because single-run holdout artifacts
# are NOT walk-forward artifacts — claiming the WF tag for them would
# dilute the precision of the corrected-WF attestation. See
# docs/phase2c/PHASE2C_6_EVALUATION_GATE_PLAN.md §3 lineage discipline.
EVALUATION_SEMANTICS_TAG = "single_run_holdout_v1"
ENGINE_CORRECTED_LINEAGE_TAG = "wf-corrected-v1"

# PHASE2C_7.1 §7 schema discriminator. Stamped on producer-side artifacts
# whose run was generated by PHASE2C_7.1 (or any direct-pattern successor
# that adopts the same regime-field convention). PHASE2C_6 artifacts on
# disk predate this schema and do NOT carry the field; the consumer
# guard treats absence-of-field as the legacy validation path.
#
# Mental model: schema_version = producer code identity, regime_key /
# regime_label = which regime the artifact attests against. The two
# axes are independent — PHASE2C_7.1 code can stamp against either
# regime, and a future schema (e.g. phase2c_8) might attest against
# regimes already in REGIME_KEY_LABEL_MAPPING.
ARTIFACT_SCHEMA_VERSION_PHASE2C_7_1 = "phase2c_7_1"

# Documented regime_key -> regime_label mapping (PHASE2C_7.1 §7).
# Single source of truth for cross-arc regime identity. Used by both
# producer (regime_label derivation from --regime-key flag) and
# consumer guard (regime_label validation against mapping). Future
# arcs adding new regimes append entries here.
#
# - v2.regime_holdout: 2022 bear regime, label config-canonical from
#   environments.yaml regime_holdout block's `label: "bear_2022"`
# - v2.validation: 2024 validation window. The validation block has
#   no `label` field in environments.yaml; "validation_2024" is a
#   PHASE2C_7.1 project convention (this mapping is the SSOT).
REGIME_KEY_LABEL_MAPPING: dict[str, str] = {
    "v2.regime_holdout": "bear_2022",
    "v2.validation": "validation_2024",
}

# Anchor git subprocess calls to the repo root containing this file, NOT
# to the caller's CWD. Without this anchor the producer guard false-rejects
# legitimate corrected runs invoked from /tmp, notebooks, CI wrappers, or
# any absolute-path launch (Codex Task 7.6 re-review finding,
# 2026-04-26).
_REPO_ROOT = Path(__file__).resolve().parents[1]


def enforce_corrected_engine_lineage() -> str:
    """Producer-side: refuse to run if HEAD doesn't contain the corrected commit.

    Returns the current HEAD SHA on success. Raises SystemExit (clear
    error message) on failure. Used by scripts that PRODUCE
    walk_forward_summary.json artifacts.

    Hard-fails (sys.exit) because callers are scripts at startup —
    aborting is the appropriate response.

    Both git subprocess calls run with cwd anchored to the repo root
    that contains this file, so the guard is independent of the
    caller's CWD. The ancestry check uses the resolved head_sha (not
    the symbolic "HEAD") so the SHA stamped into the summary metadata
    is the same SHA whose ancestry was verified — eliminating any
    HEAD-shift race between the two subprocess calls.
    """
    try:
        head_sha = subprocess.check_output(
            ["git", "rev-parse", "HEAD"], text=True, cwd=_REPO_ROOT
        ).strip()
    except subprocess.CalledProcessError as exc:
        sys.exit(
            f"ERROR: cannot resolve HEAD SHA (not in a git repo?): {exc}"
        )

    rc = subprocess.call(
        ["git", "merge-base", "--is-ancestor",
         CORRECTED_WF_ENGINE_COMMIT, head_sha],
        cwd=_REPO_ROOT,
    )
    if rc != 0:
        sys.exit(
            f"ERROR: this script requires the corrected WF engine "
            f"(commit {CORRECTED_WF_ENGINE_COMMIT} or descendant). "
            f"Current HEAD ({head_sha}) is not descended from "
            f"{CORRECTED_WF_ENGINE_COMMIT}. Refusing to run to prevent "
            f"production of pre-correction WF artifacts. See "
            f"docs/decisions/WF_TEST_BOUNDARY_SEMANTICS.md Section RS."
        )
    return head_sha


def check_wf_semantics_or_raise(
    summary: dict,
    *,
    artifact_path: str | Path | None = None,
) -> None:
    """Consumer-side: validate a WF summary is safe for RS-sensitive consumption.

    Checks both `wf_semantics == WF_SEMANTICS_TAG` and
    `corrected_wf_semantics_commit == CORRECTED_WF_ENGINE_COMMIT`.
    Distinguishes missing-field from wrong-value in the error message.
    Does NOT gate on `lineage_check` (auditor breadcrumb only, not
    load-bearing).

    Raises ValueError (not SystemExit) so consumers in notebooks /
    test harnesses / batch processors can decide how to handle the
    violation.

    Args:
        summary: The WF summary dict (typically loaded from
            walk_forward_summary.json).
        artifact_path: Optional path to the source JSON file, included
            in the error message for diagnostics. Pass when the caller
            loaded the dict from a known file path.

    Raises:
        ValueError: If wf_semantics is missing, wrong, or if
            corrected_wf_semantics_commit is missing or wrong.
    """
    where = f" at {artifact_path}" if artifact_path else ""
    actual_tag = summary.get("wf_semantics")
    if actual_tag is None:
        raise ValueError(
            f"Unsafe WF artifact{where}: missing 'wf_semantics' field "
            f"(pre-Task-7.6 artifact?). Expected {WF_SEMANTICS_TAG!r}. "
            f"Refusing per docs/decisions/WF_TEST_BOUNDARY_SEMANTICS.md "
            f"Section RS."
        )
    if actual_tag != WF_SEMANTICS_TAG:
        raise ValueError(
            f"Unsafe WF artifact{where}: wf_semantics={actual_tag!r}, "
            f"expected {WF_SEMANTICS_TAG!r}. "
            f"Refusing per docs/decisions/WF_TEST_BOUNDARY_SEMANTICS.md "
            f"Section RS."
        )
    actual_commit = summary.get("corrected_wf_semantics_commit")
    if actual_commit != CORRECTED_WF_ENGINE_COMMIT:
        raise ValueError(
            f"Unsafe WF artifact{where}: corrected_wf_semantics_commit="
            f"{actual_commit!r}, expected "
            f"{CORRECTED_WF_ENGINE_COMMIT!r}. "
            f"Refusing per docs/decisions/WF_TEST_BOUNDARY_SEMANTICS.md "
            f"Section RS."
        )


def check_evaluation_semantics_or_raise(
    summary: dict,
    *,
    artifact_path: str | Path | None = None,
) -> None:
    """Consumer-side: validate a single-run holdout summary is safe for RS-sensitive consumption.

    Companion helper to check_wf_semantics_or_raise(), but for single-run
    holdout artifacts (PHASE2C_6 evaluation gate work and PHASE2C_7.1+
    multi-regime extensions) rather than walk-forward artifacts. The two
    helpers MUST stay semantically separate — calling this helper on a
    WF artifact will reject it (it won't carry the evaluation_semantics
    tag), and calling check_wf_semantics_or_raise() on a single-run
    holdout artifact will also reject it (it won't carry the
    wf_semantics tag). This is intentional and prevents accidental
    cross-domain consumption.

    Schema discriminator (PHASE2C_7.1 §7). The artifact_schema_version
    field routes validation logic via three branches:

    1. **Absent** — legacy PHASE2C_6 schema. Validates the original five
       fields below. Backward-compatibility contract: PHASE2C_6
       artifacts on disk continue to validate without modification.
    2. **`"phase2c_7_1"`** — new schema. Validates the same five legacy
       fields, plus regime_key (against documented mapping) and
       regime_label (matched to regime_key per the mapping).
    3. **Any other value** — defensive reject. Future arcs extend the
       branching when introducing new schemas; until then any
       unrecognized value raises rather than silently falling through.

    Legacy / shared five-field validation:

    1. evaluation_semantics == EVALUATION_SEMANTICS_TAG
       ("single_run_holdout_v1")
    2. engine_commit == CORRECTED_WF_ENGINE_COMMIT ("eb1c87f")
    3. engine_corrected_lineage == ENGINE_CORRECTED_LINEAGE_TAG
       ("wf-corrected-v1")
    4. lineage_check == "passed"
    5. current_git_sha is present and non-empty

    Note on lineage_check: this helper validates lineage_check as a
    load-bearing field, unlike the WF helper which treats it as an
    auditor breadcrumb only. The asymmetry is intentional — the
    corrected-engine project arc (Task 7.5 / 7.6 / 11) empirically
    demonstrated that lineage_check round-trip validation catches real
    failure modes that pre-correction artifacts wouldn't. New
    attestation domains (single-run holdout, future validation/test
    evaluations) lock in this stricter validation from day one.

    Raises ValueError (not SystemExit) so consumers in notebooks /
    test harnesses / batch processors can decide how to handle the
    violation.

    Args:
        summary: The single-run holdout summary dict (typically loaded
            from holdout_summary.json or the per-batch aggregate
            summary).
        artifact_path: Optional path to the source JSON file, included
            in the error message for diagnostics.

    Raises:
        ValueError: If any required field is missing, wrong, empty, or
            (for new-schema artifacts) if regime_key is unknown or
            regime_label does not match the documented mapping for the
            given regime_key. The error message identifies the specific
            failing field for diagnostics.
    """
    where = f" at {artifact_path}" if artifact_path else ""

    # Five-field legacy validation runs unconditionally; both schema
    # branches share these checks.
    actual_eval_tag = summary.get("evaluation_semantics")
    if actual_eval_tag is None:
        raise ValueError(
            f"Unsafe single-run holdout artifact{where}: missing "
            f"'evaluation_semantics' field. Expected "
            f"{EVALUATION_SEMANTICS_TAG!r}. Refusing per "
            f"docs/decisions/WF_TEST_BOUNDARY_SEMANTICS.md Section RS."
        )
    if actual_eval_tag != EVALUATION_SEMANTICS_TAG:
        raise ValueError(
            f"Unsafe single-run holdout artifact{where}: "
            f"evaluation_semantics={actual_eval_tag!r}, expected "
            f"{EVALUATION_SEMANTICS_TAG!r}. Refusing per "
            f"docs/decisions/WF_TEST_BOUNDARY_SEMANTICS.md Section RS."
        )

    actual_engine_commit = summary.get("engine_commit")
    if actual_engine_commit != CORRECTED_WF_ENGINE_COMMIT:
        raise ValueError(
            f"Unsafe single-run holdout artifact{where}: "
            f"engine_commit={actual_engine_commit!r}, expected "
            f"{CORRECTED_WF_ENGINE_COMMIT!r}. Refusing per "
            f"docs/decisions/WF_TEST_BOUNDARY_SEMANTICS.md Section RS."
        )

    actual_lineage_tag = summary.get("engine_corrected_lineage")
    if actual_lineage_tag != ENGINE_CORRECTED_LINEAGE_TAG:
        raise ValueError(
            f"Unsafe single-run holdout artifact{where}: "
            f"engine_corrected_lineage={actual_lineage_tag!r}, "
            f"expected {ENGINE_CORRECTED_LINEAGE_TAG!r}. Refusing per "
            f"docs/decisions/WF_TEST_BOUNDARY_SEMANTICS.md Section RS."
        )

    actual_check = summary.get("lineage_check")
    if actual_check != "passed":
        raise ValueError(
            f"Unsafe single-run holdout artifact{where}: "
            f"lineage_check={actual_check!r}, expected 'passed'. "
            f"Refusing per docs/decisions/WF_TEST_BOUNDARY_SEMANTICS.md "
            f"Section RS."
        )

    actual_sha = summary.get("current_git_sha")
    if not actual_sha:
        raise ValueError(
            f"Unsafe single-run holdout artifact{where}: "
            f"current_git_sha={actual_sha!r} is missing or empty. "
            f"Refusing per docs/decisions/WF_TEST_BOUNDARY_SEMANTICS.md "
            f"Section RS."
        )

    # Schema discriminator: route to the new validation path only when
    # the producer explicitly stamped artifact_schema_version. Absence is
    # the legacy path (PHASE2C_6 artifacts on disk) — validated above.
    schema_version = summary.get("artifact_schema_version")
    if schema_version is None:
        return  # Legacy path complete; PHASE2C_6 backward-compat contract.

    if schema_version != ARTIFACT_SCHEMA_VERSION_PHASE2C_7_1:
        raise ValueError(
            f"Unsafe single-run holdout artifact{where}: "
            f"unrecognized artifact_schema_version={schema_version!r}. "
            f"Expected absent (legacy PHASE2C_6 schema) or "
            f"{ARTIFACT_SCHEMA_VERSION_PHASE2C_7_1!r}. Refusing per "
            f"docs/decisions/WF_TEST_BOUNDARY_SEMANTICS.md Section RS."
        )

    # New PHASE2C_7.1 schema path: regime_key + regime_label must be
    # present and consistent with the documented mapping.
    actual_regime_key = summary.get("regime_key")
    if actual_regime_key is None:
        raise ValueError(
            f"Unsafe single-run holdout artifact{where}: missing "
            f"'regime_key' field (required for "
            f"artifact_schema_version={schema_version!r}). Refusing per "
            f"docs/decisions/WF_TEST_BOUNDARY_SEMANTICS.md Section RS."
        )

    actual_regime_label = summary.get("regime_label")
    if actual_regime_label is None:
        raise ValueError(
            f"Unsafe single-run holdout artifact{where}: missing "
            f"'regime_label' field (required for "
            f"artifact_schema_version={schema_version!r}). Refusing per "
            f"docs/decisions/WF_TEST_BOUNDARY_SEMANTICS.md Section RS."
        )

    expected_label = REGIME_KEY_LABEL_MAPPING.get(actual_regime_key)
    if expected_label is None:
        raise ValueError(
            f"Unsafe single-run holdout artifact{where}: "
            f"regime_key={actual_regime_key!r} is not in the "
            f"documented mapping (known keys: "
            f"{sorted(REGIME_KEY_LABEL_MAPPING)}). Refusing per "
            f"docs/decisions/WF_TEST_BOUNDARY_SEMANTICS.md Section RS."
        )

    if actual_regime_label != expected_label:
        raise ValueError(
            f"Unsafe single-run holdout artifact{where}: "
            f"regime_label={actual_regime_label!r} does not match the "
            f"documented mapping for regime_key="
            f"{actual_regime_key!r}; expected {expected_label!r}. "
            f"Refusing per "
            f"docs/decisions/WF_TEST_BOUNDARY_SEMANTICS.md Section RS."
        )
